{
    "config": {
        "error": {
            "cannot_connect": "No se pudo conectar, por favor, int\u00e9ntalo de nuevo",
            "invalid_auth": "Autenticaci\u00f3n no v\u00e1lida",
            "unknown": "Error inesperado"
        },
        "step": {
            "user": {
                "data": {
                    "protocol": "Protocolo"
                }
            }
        }
    }
}